main: at.jellybit.mendit.MendIt
author: Daniel Englisch
name: MendIt
version: 1.0
description: Mends items using experience.
commands:
  mend:
    description: Mends item in hand if you have enough levels
    usage: Usage /mend [it]
